application: paran-yo-launchsoon
version: 1
runtime: python
api_version: 1

default_expiration: "1h"

handlers:
  
- url: /favicon\.ico
  static_files: static/ico/favicon.ico
  upload: static/ico/favicon\.ico
  expiration: "6d"

- url: /apple-touch-icon\.png
  static_files: static/ico/apple-touch-icon.ong
  upload: static/ico//apple-touch-icon\.png
  expiration: "6d"

- url: /logo/
  static_dir: static/img/logo/
  expiration: "1h"

- url: /js/
  static_dir: static/js/
  expiration: "1h"

- url: /less/
  static_dir: static/less/
  expiration: "1h"
  
- url: /less/img
  static_dir: static/img/
  expiration: "1h"
  
- url: /img/
  static_dir: static/img/
  expiration: "1h"
   
- url: /.*
  script: main.py

builtins:
- datastore_admin: on
- appstats: on